import type { AuthorizedTenantActorContext } from '@/domain/context/operation-context';
import type { ActivationAttempt, InvalidationPlan, InvalidationTask, PublicContentQuery, PublicSiteData, ResolvedSiteContext } from '@/domain/stage5/models';
import { Stage5ConflictError, Stage5ResourceUnavailableError, type Stage5Repository } from '@/ports/stage5-repository';

export interface Stage5FixtureSite { readonly data: PublicSiteData; readonly active?: boolean; readonly regionActive?: boolean }
type MutableFixtureSite = { data: PublicSiteData; active?: boolean; regionActive?: boolean };
type MutableAttempt = { -readonly [Key in keyof ActivationAttempt]: ActivationAttempt[Key] };
type MutableTask = { -readonly [Key in keyof InvalidationTask]: InvalidationTask[Key] };
export class InMemoryStage5Repository implements Stage5Repository {
  private readonly sites: MutableFixtureSite[];
  private readonly attempts: MutableAttempt[] = [];
  private readonly tasks: MutableTask[] = [];
  private readonly bypasses = new Set<string>();
  readonly audits: { action: string; siteId: string; actorId: string }[] = [];
  failNextAudit = false;
  constructor(sites: readonly Stage5FixtureSite[]) { this.sites = structuredClone(sites) as MutableFixtureSite[]; }
  async findActiveSitesByExactHostname(hostname: string) { return this.sites.filter((site) => site.active !== false && site.regionActive !== false && site.data.context.normalizedHostname === hostname).map((site) => structuredClone(site.data.context)); }
  async findPendingActivation(hostname: string, attemptId: string) { return this.attempts.some((attempt) => attempt.id === attemptId && attempt.hostname === hostname && attempt.operation === 'activate' && (attempt.status === 'pending' || attempt.status === 'processing') && ['pending', 'cloudflare_verified', 'vercel_associated'].includes(attempt.phase)); }
  async loadPublicSite(context: ResolvedSiteContext, query: PublicContentQuery) { const site = this.sites.find((candidate) => candidate.active !== false && candidate.regionActive !== false && candidate.data.context.organizationId === context.organizationId && candidate.data.context.siteId === context.siteId && candidate.data.context.normalizedHostname === context.normalizedHostname && candidate.data.context.routingVersion === context.routingVersion && candidate.data.context.contentVersion === context.contentVersion); if (site === undefined) return null; const articles = site.data.articles.filter((article) => (query.articleSlug === undefined || article.slug === query.articleSlug) && (query.categorySlug === undefined || article.categorySlug === query.categorySlug) && (query.search === undefined || `${article.title} ${article.body}`.toLocaleLowerCase().includes(query.search.toLocaleLowerCase()))); return structuredClone({ ...site.data, articles }); }
  async isCacheBypassed(context: ResolvedSiteContext) { return this.bypasses.has(`${context.organizationId}:${context.siteId}`); }
  private authorize(actor: AuthorizedTenantActorContext) { if (!actor.permissionSet.has('sites.manage')) throw new Stage5ResourceUnavailableError(); }
  async beginActivation(actor: AuthorizedTenantActorContext, siteId: string, hostname: string, previousHostname: string | null, now: string) { this.authorize(actor); const current = this.attempts.find((attempt) => attempt.siteId === siteId && attempt.operation === 'activate' && (attempt.status === 'pending' || attempt.status === 'processing')); if (current !== undefined) { if (current.hostname !== hostname) throw new Stage5ConflictError(); return structuredClone(current); } const site = this.sites.find((candidate) => candidate.data.context.organizationId === actor.organizationId && candidate.data.context.siteId === siteId && candidate.data.context.normalizedHostname === hostname); if (site === undefined) throw new Stage5ResourceUnavailableError(); if (previousHostname !== null && (!this.attempts.some((attempt) => attempt.organizationId === actor.organizationId && attempt.siteId === siteId && attempt.hostname === previousHostname) || this.sites.some((candidate) => candidate.data.context.siteId !== siteId && candidate.data.context.normalizedHostname === previousHostname))) throw new Stage5ConflictError('Previous hostname is not owned by Site'); if (this.sites.some((candidate) => candidate !== site && candidate.active !== false && candidate.data.context.normalizedHostname === hostname)) throw new Stage5ConflictError(); site.active = false; const attempt: MutableAttempt = { id: crypto.randomUUID(), organizationId: actor.organizationId, siteId, hostname, previousHostname, operation: 'activate', phase: 'pending', status: 'pending', attempts: 0, nextAttemptAt: now, claimToken: null, claimExpiresAt: null, externalStatus: {} }; this.attempts.push(attempt); this.audit(actor, 'site.activation.request', siteId); return structuredClone(attempt); }
  async updateActivation(actor: AuthorizedTenantActorContext, attemptId: string, phase: ActivationAttempt['phase'], externalStatus: Readonly<Record<string, unknown>>, now: string) { this.authorize(actor); const index = this.attempts.findIndex((attempt) => attempt.id === attemptId && attempt.organizationId === actor.organizationId && attempt.status !== 'completed' && attempt.status !== 'failed'); const current = this.attempts[index]; if (current === undefined) throw new Stage5ResourceUnavailableError(); const updated: MutableAttempt = { ...current, phase, status: phase === 'completed' ? 'completed' : 'processing', externalStatus: structuredClone(externalStatus), nextAttemptAt: now }; this.attempts[index] = updated; return structuredClone(updated); }
  async failActivation(actor: AuthorizedTenantActorContext, attemptId: string, failure: Readonly<Record<string, unknown>>, nextAttemptAt: string, terminal: boolean, now: string) { void now; this.authorize(actor); const attempt = this.attempts.find((item) => item.id === attemptId && item.organizationId === actor.organizationId); if (attempt === undefined) throw new Stage5ResourceUnavailableError(); attempt.attempts += 1; attempt.status = terminal ? 'failed' : 'pending'; if (terminal) attempt.phase = 'failed'; attempt.nextAttemptAt = nextAttemptAt; attempt.claimToken = null; attempt.claimExpiresAt = null; attempt.externalStatus = structuredClone(failure); return structuredClone(attempt); }
  async claimActivationAttempts(now: string, limit: number, claimToken: string, claimExpiresAt: string) { const attempts = this.attempts.filter((attempt) => (attempt.status === 'pending' || attempt.status === 'processing') && attempt.nextAttemptAt <= now && (attempt.claimExpiresAt === null || attempt.claimExpiresAt <= now)).slice(0, Math.max(1, limit)); for (const attempt of attempts) { attempt.status = 'processing'; attempt.claimToken = claimToken; attempt.claimExpiresAt = claimExpiresAt; } return structuredClone(attempts); }
  private audit(actor: AuthorizedTenantActorContext, action: string, siteId: string) { if (this.failNextAudit) { this.failNextAudit = false; throw new Error('Injected audit failure'); } this.audits.push({ action, siteId, actorId: actor.actorId }); }
  async completeActivation(actor: AuthorizedTenantActorContext, attemptId: string, plan: InvalidationPlan, now: string) { this.authorize(actor); const attempt = this.attempts.find((item) => item.id === attemptId && item.phase === 'probe_verified' && item.operation === 'activate'); const site = this.sites.find((item) => item.data.context.siteId === attempt?.siteId && item.data.context.organizationId === actor.organizationId); if (attempt === undefined || site === undefined) throw new Stage5ConflictError(); const old = structuredClone(site); const nextContext = { ...site.data.context, routingVersion: site.data.context.routingVersion + 1 }; try { this.audit(actor, 'site.activation.complete', site.data.context.siteId); site.active = true; site.data = { ...site.data, context: nextContext }; attempt.phase = 'completed'; attempt.status = 'completed'; attempt.claimToken = null; attempt.claimExpiresAt = null; this.enqueue(plan, now); return structuredClone(nextContext); } catch (error) { Object.assign(site, old); throw error; } }
  async deactivateSite(actor: AuthorizedTenantActorContext, siteId: string, hostname: string, plan: InvalidationPlan, now: string) { this.authorize(actor); const existing = this.attempts.find((attempt) => attempt.siteId === siteId && attempt.operation === 'deactivate' && (attempt.status === 'pending' || attempt.status === 'processing')); if (existing !== undefined) return structuredClone(existing); const site = this.sites.find((item) => item.active !== false && item.data.context.organizationId === actor.organizationId && item.data.context.siteId === siteId && item.data.context.normalizedHostname === hostname); if (site === undefined) throw new Stage5ResourceUnavailableError(); const old = site.active !== false; try { this.audit(actor, 'site.deactivate', siteId); site.active = false; this.enqueue(plan, now); const attempt: MutableAttempt = { id: crypto.randomUUID(), organizationId: actor.organizationId, siteId, hostname, previousHostname: hostname, operation: 'deactivate', phase: 'deactivating', status: 'pending', attempts: 0, nextAttemptAt: now, claimToken: null, claimExpiresAt: null, externalStatus: {} }; this.attempts.push(attempt); return structuredClone(attempt); } catch (error) { site.active = old; throw error; } }
  async completeDeactivation(actor: AuthorizedTenantActorContext, attemptId: string, now: string) { void now; this.authorize(actor); const attempt = this.attempts.find((item) => item.id === attemptId && item.operation === 'deactivate'); if (attempt === undefined) throw new Stage5ResourceUnavailableError(); attempt.phase = 'completed'; attempt.status = 'completed'; attempt.claimToken = null; attempt.claimExpiresAt = null; }
  private task(plan: InvalidationPlan, now: string): MutableTask { return { ...structuredClone(plan), id: crypto.randomUUID(), attempts: 0, nextAttemptAt: now, status: 'pending', claimToken: null, claimExpiresAt: null, sanitizedFailure: null }; }
  private enqueue(plan: InvalidationPlan, now: string): MutableTask { const task = this.task(plan, now); this.tasks.push(task); this.bypasses.add(`${task.organizationId}:${task.siteId}`); return task; }
  async createInvalidation(plan: InvalidationPlan, now: string) { return structuredClone(this.enqueue(plan, now)); }
  async claimInvalidations(now: string, limit: number) { const token = crypto.randomUUID(); const expires = new Date(Date.parse(now) + 30_000).toISOString(); const claimed = this.tasks.filter((task) => (task.status === 'pending' || task.status === 'processing') && task.nextAttemptAt <= now && (task.claimExpiresAt === null || task.claimExpiresAt <= now)).slice(0, Math.max(1, limit)); for (const task of claimed) { task.status = 'processing'; task.claimToken = token; task.claimExpiresAt = expires; } return structuredClone(claimed); }
  async completeInvalidation(claimed: InvalidationTask, now: string) { const task = this.tasks.find(({ id }) => id === claimed.id); if (task === undefined || task.status !== 'processing' || task.claimToken === null || task.claimToken !== claimed.claimToken || task.claimExpiresAt! <= now) throw new Stage5ConflictError('stale_claim'); task.status = 'completed'; task.claimToken = null; task.claimExpiresAt = null; task.sanitizedFailure = null; if (!this.tasks.some((candidate) => candidate.organizationId === task.organizationId && candidate.siteId === task.siteId && candidate.status !== 'completed')) this.bypasses.delete(`${task.organizationId}:${task.siteId}`); }
  async failInvalidation(claimed: InvalidationTask, failure: Readonly<Record<string, unknown>>, nextAttemptAt: string, terminal: boolean, now: string) { const task = this.tasks.find(({ id }) => id === claimed.id); if (task === undefined || task.status !== 'processing' || task.claimToken === null || task.claimToken !== claimed.claimToken || task.claimExpiresAt! <= now) throw new Stage5ConflictError('stale_claim'); task.status = terminal ? 'failed' : 'pending'; task.attempts += 1; task.nextAttemptAt = nextAttemptAt; task.claimToken = null; task.claimExpiresAt = null; task.sanitizedFailure = structuredClone(failure); this.bypasses.add(`${task.organizationId}:${task.siteId}`); }
  snapshot() { return structuredClone({ sites: this.sites, attempts: this.attempts, tasks: this.tasks, audits: this.audits, bypasses: [...this.bypasses] }); }
}
