import { describe, expect, it } from 'vitest';
import { DomainProvisioningService } from '@/application/stage5/domain-provisioning-service';
import { HostnameResolver } from '@/application/stage5/hostname-resolver';
import { InvalidationDispatcher, planInvalidation } from '@/application/stage5/invalidation';
import { createStage7ReadinessFixture } from '@/domain/stage7/readiness-fixtures';
import { createStage5E2eRepository } from '@/infrastructure/testing/stage5-fixture';
import type { CloudflareAuthorityPort } from '@/ports/cloudflare';
import type { VercelHostingPort } from '@/ports/vercel-domain';

import { stage7RuntimeConfig } from '../helpers/stage7';

const config = stage7RuntimeConfig();
const readinessFixture = createStage7ReadinessFixture(config);
const alphaSite = readinessFixture.roots[0].apexSite;
const actor = { actorType: 'user' as const, actorId: 'user', verifiedAuthUserId: 'auth', organizationId: alphaSite.organizationId, permissionSet: new Set(['sites.manage']), entryPoint: 'cms' as const, requestId: 'request' };
class CloudflareFake implements CloudflareAuthorityPort { readonly authority = 'nameservers_dns_wildcard_ssl_proxy_cdn' as const; operations: string[] = []; async check() { return { service: 'cloudflare', status: 'healthy' as const }; } async verifyZone(hostname: string) { this.operations.push(`verify:${hostname}`); return { hostname, nameserversAuthoritative: true, publicDelegationAuthoritative: true, apexProxied: true, wildcardProxied: true, sslMode: 'full_strict' as const }; } async ensureExactVerificationTxt(_host: string, name: string) { this.operations.push(`txt:add:${name}`); } async removeExactVerificationTxt(_host: string, name: string) { this.operations.push(`txt:remove:${name}`); } async purgeExactUrls(urls: readonly string[]) { this.operations.push(`purge:${urls.length}`); } async purgeHostname(host: string) { this.operations.push(`purge-host:${host}`); } }
class VercelFake implements VercelHostingPort { readonly projectCount = 1 as const; readonly responsibility = 'application_hosting_only' as const; operations: string[] = []; async check() { return { service: 'vercel', status: 'healthy' as const }; } async associateExactDomain(hostname: string) { this.operations.push(`associate-exact:${hostname}`); return { hostname, associated: true, verified: false, verificationChallenge: { type: 'TXT' as const, name: `_vercel.${hostname}`, value: 'proof' } }; } async removeExactDomain(hostname: string) { this.operations.push(`remove-exact:${hostname}`); } async verifyExactDomain(hostname: string) { this.operations.push(`verify-exact:${hostname}`); return true; } }

describe('Stage 5 hostname activation and invalidation integration', () => {
  it('classifies malformed, reserved, unknown, exact active, and deactivated hosts safely', async () => { const repo = createStage5E2eRepository(config); const resolver = new HostnameResolver(repo, { cms: 'indicate.web.id', api: 'api.indicate.web.id', webhook: 'webhook.indicate.web.id' }); expect((await resolver.classify(null)).kind).toBe('invalid'); expect((await resolver.classify('indicate.web.id')).kind).toBe('control'); expect((await resolver.classify('evil.alpha.example.web.id')).kind).toBe('unknown'); expect((await resolver.classify('alpha.example.web.id')).kind).toBe('site'); const plan = planInvalidation({ kind: 'hostname', organizationId: actor.organizationId, siteId: alphaSite.id, previousHostname: 'alpha.example.web.id', currentHostname: null }); await repo.deactivateSite(actor, alphaSite.id, 'alpha.example.web.id', plan, new Date().toISOString()); expect((await resolver.classify('alpha.example.web.id')).kind).toBe('unknown'); });
  it('uses only Cloudflare authority and exact Vercel operations in a resumable audited activation saga', async () => { const repo = createStage5E2eRepository(config); await repo.deactivateSite(actor, alphaSite.id, 'alpha.example.web.id', planInvalidation({ kind: 'hostname', organizationId: actor.organizationId, siteId: alphaSite.id, previousHostname: 'alpha.example.web.id', currentHostname: null }), new Date().toISOString()); const cloudflare = new CloudflareFake(); const vercel = new VercelFake(); const service = new DomainProvisioningService(repo, cloudflare, vercel, { verifyPendingHostname: async () => true }, new Set(['indicate.web.id', 'api.indicate.web.id', 'webhook.indicate.web.id'])); const result = await service.activate(actor, alphaSite.id, 'ALPHA.EXAMPLE.WEB.ID.'); expect(result.normalizedHostname).toBe('alpha.example.web.id'); expect(vercel.operations).toEqual(expect.arrayContaining(['associate-exact:alpha.example.web.id', 'verify-exact:alpha.example.web.id'])); expect(vercel.operations.join(' ')).not.toMatch(/nameserver|wildcard|\*/i); expect(cloudflare.authority).toBe('nameservers_dns_wildcard_ssl_proxy_cdn'); expect(repo.snapshot().audits.map(({ action }) => action)).toContain('site.activation.complete'); });
  it('rejects a reserved previous hostname before persisting an activation attempt', async () => {
    const repo = createStage5E2eRepository(config);
    const service = new DomainProvisioningService(repo, new CloudflareFake(), new VercelFake(), { verifyPendingHostname: async () => true }, new Set(['indicate.web.id']));
    await expect(service.activate(actor, alphaSite.id, 'alpha.example.web.id', new Date('2026-01-01T00:00:00.000Z'), 'indicate.web.id')).rejects.toThrow('CONFIGURATION_INVALID');
    expect(repo.snapshot().attempts).toHaveLength(0);
  });

  it('dispatches complete invalidation and enables Site bypass on provider failure', async () => { const repo = createStage5E2eRepository(config); const plan = planInvalidation({ kind: 'site_settings', organizationId: actor.organizationId, siteId: alphaSite.id, hostname: 'alpha.example.web.id' }); await repo.createInvalidation(plan, '2026-01-01T00:00:00.000Z'); const bypass: boolean[] = []; const cloudflare = new CloudflareFake(); const dispatcher = new InvalidationDispatcher(repo, { revalidateTags: async () => undefined, revalidatePaths: async () => undefined }, { incrementSiteVersion: async () => undefined, setSiteBypass: async (_org, _site, enabled) => { bypass.push(enabled); } }, cloudflare, [1], 2); expect(await dispatcher.dispatch(new Date('2026-01-01T00:00:00.000Z'), 10)).toEqual({ completed: 1, failed: 0 }); expect(bypass).toEqual([false]); await repo.createInvalidation(plan, '2026-01-01T00:00:01.000Z'); cloudflare.purgeExactUrls = async () => { throw new Error('offline'); }; expect(await dispatcher.dispatch(new Date('2026-01-01T00:00:01.000Z'), 10)).toEqual({ completed: 0, failed: 1 }); expect(bypass.at(-1)).toBe(true); });
});
