/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import type { ReactNode } from 'react';
import { buildSeoDocument, serializeJsonLd } from '@/application/stage5/seo';
import type { PublicArticle, PublicSiteData } from '@/domain/stage5/models';

export function ArticleCard({ article }: { readonly article: PublicArticle }) { return <article className="public-card"><div className="media-frame" aria-hidden={article.imageUrl === null}>{article.imageUrl === null ? <span>INDICATE</span> : <img src={article.imageUrl} alt="" width={article.imageWidth ?? 1200} height={article.imageHeight ?? 675} />}</div><p className="article-kicker">{article.categoryName ?? 'Berita'}</p><h2><Link href={`/articles/${article.slug}`}>{article.title}</Link></h2><p>{article.description}</p><p className="article-meta">{article.attribution} · <time dateTime={article.publishedAt}>{new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(article.publishedAt))}</time></p></article>; }
export function PublicTemplate({ site, children }: { readonly site: PublicSiteData; readonly children: ReactNode }) { const primary = site.settings.colors.primary ?? '#0b5d4b'; const accent = site.settings.colors.accent ?? '#e9a23b'; return <div className="public-shell" style={{ '--site-primary': primary, '--site-accent': accent } as React.CSSProperties}><a className="skip-link" href="#main-content">Lewati ke konten</a><header className="public-header"><div className="public-brand">{site.settings.logoUrl === null ? <span className="brand-mark" aria-hidden="true">I</span> : <img src={site.settings.logoUrl} alt="" width="48" height="48" />}<Link href="/" aria-label={`${site.settings.name} beranda`}><strong>{site.settings.name}</strong><small>{site.settings.description}</small></Link></div><nav aria-label="Navigasi utama">{site.settings.navigation.map((item) => <Link href={item.path} key={`${item.path}:${item.label}`}>{item.label}</Link>)}<Link href="/search">Cari</Link></nav></header><main id="main-content">{children}</main><footer className="public-footer"><strong>{site.settings.name}</strong><p>{site.settings.description}</p><div>{Object.entries(site.settings.socialLinks).map(([name, href]) => <a href={href} key={name} rel="noopener noreferrer">{name}</a>)}</div><small>© {new Date().getUTCFullYear()} {site.settings.name}</small></footer></div>; }
export function ListingPage({ site, title, description }: { readonly site: PublicSiteData; readonly title: string; readonly description?: string }) { const seo = buildSeoDocument(site, { path: '/' }); return <PublicTemplate site={site}><section className="hero"><p className="eyebrow">Berita lokal terpercaya</p><h1>{title}</h1><p>{description ?? site.settings.description}</p></section><div className="public-layout"><section className="article-grid" aria-label={title}>{site.articles.length === 0 ? <div className="public-empty" role="status"><h2>Belum ada berita</h2><p>Konten untuk situs ini belum tersedia.</p></div> : site.articles.map((article) => <ArticleCard article={article} key={article.id} />)}</section><aside className="public-sidebar" aria-label="Informasi situs"><h2>Tentang {site.settings.name}</h2><p>{site.settings.description}</p><Link href="/rss.xml">Ikuti RSS</Link></aside></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(seo.jsonLd) }} /></PublicTemplate>; }
export function ArticlePage({ site, article }: { readonly site: PublicSiteData; readonly article: PublicArticle }) { const seo = buildSeoDocument(site, { path: `/articles/${article.slug}`, article }); return <PublicTemplate site={site}><article className="article-detail"><nav aria-label="Breadcrumb"><Link href="/">Beranda</Link> / {article.categorySlug === null ? null : <><Link href={`/categories/${article.categorySlug}`}>{article.categoryName}</Link> / </>}<span>{article.title}</span></nav><p className="article-kicker">{article.categoryName ?? 'Berita'}</p><h1>{article.title}</h1><p className="article-meta">{article.attribution}{article.publisherVerified ? ' · Terverifikasi' : ''}{article.independent ? ' · Media independen' : ''}</p>{article.imageUrl === null ? null : <div className="article-hero-media"><img src={article.imageUrl} alt="" width={article.imageWidth ?? 1200} height={article.imageHeight ?? 675} /></div>}<div className="article-body">{article.body.split(/\n{2,}/u).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(seo.jsonLd) }} /></article></PublicTemplate>; }
