'use client';

import { useEffect, useMemo, useState } from 'react';
import { Archive, ArchiveRestore, ChevronRight, FileText, Loader2, Search, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import type { DashboardCommand } from '@/modules/dashboard/command';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { EmptyState } from '@/modules/dashboard/components/empty-state';
import { DashboardPager } from '@/modules/dashboard/components/shared/dashboard-pager';
import { SearchCombobox } from '@/modules/dashboard/components/shared/search-combobox';
import { useDashboardPage } from '@/modules/dashboard/components/shared/use-dashboard-query';
import { STATUS_BADGE_TONE, resolveStatus } from '@/modules/dashboard/components/data-view-format';

type Row={readonly id:string;readonly title:string;readonly slug:string;readonly status:string;readonly publishedAt?:string|null;readonly version:number;readonly portalHostnames?:readonly string[];readonly tags?:readonly string[];readonly organizationId?:string;readonly orgName?:string};
const statuses=[{value:'',label:'Semua status'},{value:'active',label:'Aktif'},{value:'draft',label:'Draf'},{value:'in_review',label:'Tinjau'},{value:'scheduled',label:'Jadwal'},{value:'archived',label:'Arsip'}];
function dateLabel(v:string|null|undefined){if(!v)return 'Belum tayang';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});}

export function ContentLibraryV2({data,command,onFilterApply,articlesNextCursor,articlesTotal,onLoadMoreArticles,crossOrg,onEditArticle}:{
readonly data:unknown;readonly command?:DashboardCommand|undefined;readonly onFilterApply?:(q:string)=>void|undefined;readonly articlesNextCursor?:string|null|undefined;readonly articlesTotal?:number|undefined;readonly onLoadMoreArticles?:(()=>Promise<{readonly loaded:number;readonly total:number;readonly nextCursor:string|null}|null>)|undefined;readonly crossOrg?:boolean|undefined;readonly onEditArticle?:(id:string,ownerOrganizationId?:string)=>void|undefined;
}){
 const model=(data??{}) as {readonly articles?:readonly Row[];readonly total?:number;readonly articlesNextCursor?:string|null};
 const rows=useMemo(()=>[...(model.articles??[])],[model.articles]);const total=model.total??articlesTotal??rows.length;const cursor=model.articlesNextCursor??articlesNextCursor??null;
 const [page,setPage]=useDashboardPage('archivePage');const [search,setSearch]=useState('');const [status,setStatus]=useState('active');const [sort,setSort]=useState('published-desc');const [selected,setSelected]=useState<readonly string[]>([]);const [busy,setBusy]=useState<readonly string[]>([]);
 useEffect(()=>{if(!onFilterApply)return;const t=window.setTimeout(()=>{const parts=['status='+encodeURIComponent(status),'sort='+encodeURIComponent(sort)];if(search.trim())parts.push('search='+encodeURIComponent(search.trim()));onFilterApply('&'+parts.join('&'));setPage(1);},300);return()=>window.clearTimeout(t);},[search,status,sort,onFilterApply,setPage]);
 const count=Math.max(1,Math.ceil(rows.length/20));const safe=Math.min(page,count);const visible=rows.slice((safe-1)*20,safe*20);const ids=visible.map(r=>r.id);const selectedVisible=ids.filter(id=>selected.includes(id));
 const togglePage=()=>setSelected(x=>selectedVisible.length===ids.length?x.filter(id=>!ids.includes(id)):[...new Set([...x,...ids])]);
 const run=async(row:Row,action:'article.archive'|'article.restore'|'article.delete',refresh=true)=>{if(!command||busy.includes(row.id))return;setBusy(x=>[...x,row.id]);try{const owner=crossOrg&&row.organizationId?{ownerOrganizationId:row.organizationId}:{};await command(action,{id:row.id,expectedVersion:row.version,...owner},{refresh});toast.success(action==='article.archive'?'Artikel diarsipkan.':action==='article.restore'?'Artikel dipulihkan.':'Artikel dihapus.');}catch(e){toast.error(e instanceof Error?e.message:'Aksi artikel gagal.')}finally{setBusy(x=>x.filter(id=>id!==row.id));}};
  const edit=(row:Row)=>{if(crossOrg){if(!row.organizationId){toast.error('Organisasi pemilik artikel tidak tersedia. Muat ulang daftar artikel.');return;}onEditArticle?.(row.id,row.organizationId);return;}onEditArticle?.(row.id);};
  const archiveSelected = async () => {
    const selectedRows = visible.filter((row) => selectedVisible.includes(row.id));
    for (const [index, row] of selectedRows.entries()) {
      await run(row, 'article.archive', index === selectedRows.length - 1);
    }
  };
 return <section aria-label="Content Library" className="space-y-5">
  <header className="rounded-xl border border-hairline bg-bg-raised/60 p-5"><p className="m-0 font-mono text-[10px] uppercase tracking-[.18em] text-brass">04 / Content Library</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="m-0 text-2xl font-semibold text-paper">Content Library</h1><p className="m-0 mt-1 text-sm text-paper-faint">Inventory artikel jaringan dengan filter, coverage portal, status, dan handoff ke Editorial Workspace.</p></div><Badge variant="outline" className="font-mono text-[10px] uppercase">{total.toLocaleString('id-ID')} artikel</Badge></div></header>
  <div className="rounded-lg border border-hairline bg-bg-raised p-3"><div className="grid gap-2 lg:grid-cols-[1fr_180px_180px_auto]"><div className="relative"><Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-paper-faint"/><Input aria-label="Cari artikel" className="pl-8" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari judul atau slug"/></div><SearchCombobox aria-label="Status artikel" value={status} onValueChange={v=>setStatus(v??'')} options={statuses} placeholder="Status"/><SearchCombobox aria-label="Urutan artikel" value={sort} onValueChange={v=>setSort(v??'published-desc')} options={[{value:'published-desc',label:'Terbaru tayang'},{value:'updated',label:'Terakhir diubah'},{value:'title',label:'Judul A–Z'},{value:'syndicated',label:'Portal terbanyak'}]} placeholder="Urutan"/><Button variant="ghost" onClick={()=>{setSearch('');setStatus('active');setSort('published-desc');setSelected([])}}>Reset</Button></div></div>
  {selectedVisible.length?<div role="status" className="flex gap-2 rounded-lg border border-brass/40 bg-bg-raised p-3"><span className="mr-auto text-xs text-paper-dim">{selectedVisible.length} terpilih</span><Button size="sm" variant="outline" disabled={selectedVisible.some(id=>busy.includes(id))} onClick={()=>void archiveSelected()}>Arsipkan</Button><Button size="sm" variant="ghost" onClick={()=>setSelected([])}>Batal</Button></div>:null}
  {visible.length===0?<EmptyState title="Tidak ada artikel yang cocok." description="Ubah filter atau muat ulang data dari server."/>:<div className="overflow-x-auto rounded-lg border border-hairline bg-bg-raised"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-hairline text-left font-mono text-[10px] uppercase text-paper-faint"><th className="w-10 p-3"><Checkbox checked={selectedVisible.length===ids.length} indeterminate={selectedVisible.length>0&&selectedVisible.length<ids.length} onCheckedChange={togglePage} aria-label="Pilih artikel halaman"/></th><th className="p-3">Artikel</th><th className="p-3">Status</th><th className="p-3">Portal</th><th className="p-3">Tayang</th><th className="p-3 text-right">Aksi</th></tr></thead><tbody>{visible.map(row=>{const meta=resolveStatus(row.status);const isBusy=busy.includes(row.id);const transition=row.status==='archived'?'article.restore':'article.archive';return <tr key={row.id} className="border-b border-hairline/60 hover:bg-bg-raised-2"><td className="p-3"><Checkbox checked={selected.includes(row.id)} onCheckedChange={()=>setSelected(x=>x.includes(row.id)?x.filter(id=>id!==row.id):[...x,row.id])} aria-label={'Pilih artikel '+row.title} disabled={isBusy}/></td><td className="p-3"><div className="flex gap-2"><FileText className="mt-1 h-4 w-4 flex-none text-brass"/><div className="min-w-0"><button className="block max-w-[38rem] truncate text-left font-medium text-paper hover:text-brass" onClick={()=>edit(row)}>{row.title}</button><p className="m-0 font-mono text-[10px] text-paper-faint">{row.slug}</p>{crossOrg&&row.orgName?<p className="m-0 text-[11px] text-paper-dim">{row.orgName}</p>:null}{row.tags?.length?<p className="m-0 text-[10px] text-paper-faint">{row.tags.slice(0,3).join(' · ')}</p>:null}</div></div></td><td className="p-3"><Badge variant="outline" className={STATUS_BADGE_TONE[meta.tone]}>{meta.label}</Badge></td><td className="p-3 font-mono text-xs text-paper-dim">{row.portalHostnames?.length??0} portal</td><td className="p-3 whitespace-nowrap text-xs text-paper-dim">{dateLabel(row.publishedAt)}</td><td className="p-3 text-right"><Button variant="ghost" size="icon-xs" aria-label={'Ubah artikel '+row.title} onClick={()=>edit(row)} disabled={isBusy}><ChevronRight className="h-4 w-4"/></Button><Button variant="ghost" size="icon-xs" aria-label={(row.status==='archived'?'Pulihkan':'Arsipkan')+' artikel '+row.title} onClick={()=>void run(row,transition)} disabled={isBusy}>{isBusy?<Loader2 className="h-4 w-4 animate-spin"/>:row.status==='archived'?<ArchiveRestore className="h-4 w-4"/>:<Archive className="h-4 w-4"/>}</Button><Button variant="ghost" size="icon-xs" className="text-error" aria-label={'Hapus permanen artikel '+row.title} onClick={()=>void run(row,'article.delete')} disabled={isBusy}><Trash2 className="h-4 w-4"/></Button></td></tr>})}</tbody></table></div>}
  <DashboardPager startIndex={(safe-1)*20} visibleCount={visible.length} total={total} page={safe} pageCount={count} onPageChange={setPage}/>
  {cursor!==null&&onLoadMoreArticles?<div className="flex justify-center"><Button variant="outline" onClick={()=>void onLoadMoreArticles()}>Muat artikel lebih lama</Button></div>:null}
 </section>;
}