// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ContentLibraryV2 } from './content-library-v2';
vi.mock('@/modules/dashboard/components/shared/use-dashboard-query', () => ({ useDashboardPage: () => [1, vi.fn()] }));
afterEach(()=>cleanup());
const DATA={articles:[{id:'a-1',title:'Banjir Wonosobo',slug:'banjir-wonosobo',status:'active',publishedAt:'2026-10-01T00:00:00Z',tags:['bencana'],portalHostnames:['fakta01.my.id'],version:2}],total:1,articlesNextCursor:null};
describe('ContentLibraryV2',()=>{it('renders V2 inventory and server filters',async()=>{const u=userEvent.setup();const f=vi.fn();render(<ContentLibraryV2 data={DATA} onFilterApply={f}/>);expect(screen.getByRole('region',{name:'Content Library'})).toBeDefined();expect(screen.getByText('Banjir Wonosobo')).toBeDefined();await u.type(screen.getByLabelText('Cari artikel'),'apbd');await waitFor(()=>expect(f).toHaveBeenCalledWith('&status=active&sort=published-desc&search=apbd'),{timeout:1500});});it('hands edit to Editorial Workspace and archive command to production',async()=>{const u=userEvent.setup();const c=vi.fn(async()=>({id:'a-1',version:3}));const e=vi.fn();render(<ContentLibraryV2 data={DATA} command={c} onEditArticle={e}/>);await u.click(screen.getByRole('button',{name:'Ubah artikel Banjir Wonosobo'}));expect(e).toHaveBeenCalledWith('a-1');await u.click(screen.getByRole('button',{name:'Arsipkan artikel Banjir Wonosobo'}));await waitFor(()=>expect(c).toHaveBeenCalledWith('article.archive',{id:'a-1',expectedVersion:2},{refresh:true}));});it('supports selection and empty state',async()=>{const u=userEvent.setup();const {unmount}=render(<ContentLibraryV2 data={DATA}/>);await u.click(screen.getByRole('checkbox',{name:'Pilih artikel halaman'}));expect(screen.getAllByRole('status').some(node => node.textContent?.includes('1 terpilih'))).toBe(true);unmount();render(<ContentLibraryV2 data={{articles:[],total:0}}/>);expect(screen.getByText('Tidak ada artikel yang cocok.')).toBeDefined();});});
