import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { ArticlePage, ListingPage, PublicTemplate } from '@/app/public-template';
import { buildSeoDocument, serializeJsonLd, serializeRobots, serializeRss, serializeSitemap } from '@/application/stage5/seo';
import { cacheEntryMatches, createCacheIdentity, redisCacheNamespace } from '@/application/stage5/cache-identity';
import { createStage5E2eRepository } from '@/infrastructure/testing/stage5-fixture';

describe('Stage 5 public UI, SEO, and cache safety', () => {
  async function fixture() { const repo = createStage5E2eRepository(); const context = (await repo.findActiveSitesByExactHostname('alpha.example.web.id'))[0]!; return (await repo.loadPublicSite(context, {}))!; }
  it('renders every shared public surface with semantic navigation, dimensions, safe text, and focus target', async () => { const site = await fixture(); const listing = renderToStaticMarkup(<ListingPage site={site} title="Berita terbaru" />); const article = renderToStaticMarkup(<ArticlePage site={site} article={site.articles[0]!} />); expect(listing).toContain('Lewati ke konten'); expect(listing).toContain('Navigasi utama'); expect(listing).toContain('<header'); expect(listing).toContain('<aside'); expect(listing).toContain('<footer'); expect(article).toContain('Breadcrumb'); expect(article).toContain('application/ld+json'); expect(listing).not.toContain('<script>alert'); });
  it('renders a Site-safe empty state and persists only supplied branding', async () => { const site = await fixture(); const empty = { ...site, articles: [] }; const html = renderToStaticMarkup(<PublicTemplate site={empty}><div role="status">Belum tersedia</div></PublicTemplate>); expect(html).toContain('Alpha News'); expect(html).toContain('Belum tersedia'); expect(html).not.toContain('Wonosobo Alpha'); });
  it('builds parseable, hostname-correct SEO and noindex failure documents', async () => { const site = await fixture(); const article = site.articles[0]!; const document = buildSeoDocument(site, { path: `/articles/${article.slug}`, article }); expect(new URL(document.canonical!).hostname).toBe(site.context.normalizedHostname); expect(() => JSON.parse(serializeJsonLd(document.jsonLd))).not.toThrow(); expect(serializeRobots(site)).toContain(`https://${site.context.normalizedHostname}/sitemap.xml`); expect(serializeSitemap(site)).toContain(site.context.normalizedHostname); expect(serializeRss(site)).toContain(site.context.normalizedHostname); expect(buildSeoDocument(site, { path: '/missing', indexable: false })).toMatchObject({ canonical: null, robots: 'noindex, nofollow', jsonLd: [] }); });
  it('validates embedded cache context and tenant-scoped Redis namespaces', async () => { const site = await fixture(); const identity = createCacheIdentity({ context: site.context, locale: 'id-ID', path: '/', query: {}, preview: false, authClass: 'anonymous' })!; expect(cacheEntryMatches(identity, site.context)).toBe(true); expect(cacheEntryMatches(identity, { ...site.context, siteId: 'foreign' })).toBe(false); expect(redisCacheNamespace('production', 'org', 'site')).toBe('indicate:production:v1:cache:org:site'); });
});
