export function createValidRuntimeEnvironment(
  overrides: Record<string, string | undefined> = {},
): Record<string, string | undefined> {
  return {
    NODE_ENV: 'test',
    APP_ENVIRONMENT: 'test',
    SCHEMA_GATE_MODE: 'contract',
    CMS_HOST: 'indicate.web.id',
    API_HOST: 'api.indicate.web.id',
    WEBHOOK_HOST: 'webhook.indicate.web.id',
    MVP_ROOT_HOSTS: 'alpha.example.web.id,beta.example.web.id,gamma.example.web.id',
    NEXT_PUBLIC_SUPABASE_URL: 'https://abcdefghijklmnop.supabase.co',
    NEXT_PUBLIC_SUPABASE_ANON_KEY: 'public-anon-value',
    SUPABASE_PROJECT_REF: 'abcdefghijklmnop',
    SUPABASE_SERVICE_ROLE_KEY: 'service-role-secret',
    DATABASE_POOL_URL: 'postgresql://indicate_runtime.abcdefghijklmnop:password@aws-0-region.pooler.supabase.com:6543/postgres',
    DATABASE_DIRECT_URL: 'postgresql://postgres:password@db.abcdefghijklmnop.supabase.co:5432/postgres',
    CLOUDFLARE_ACCOUNT_ID: 'cloudflare-account',
    CLOUDFLARE_API_TOKEN: 'cloudflare-secret',
    CLOUDFLARE_ORIGIN_SECRET: 'cloudflare-origin-secret',
    CLOUDFLARE_ZONE_IDS: 'zone-alpha,zone-beta,zone-gamma',
    CLOUDFLARE_EXPECTED_NAMESERVERS: 'ada.ns.cloudflare.com,bob.ns.cloudflare.com',
    CLOUDFLARE_SSL_MODE: 'full_strict',
    VERCEL_PROJECT_ID: 'vercel-project',
    VERCEL_TEAM_ID: 'vercel-team',
    VERCEL_API_TOKEN: 'vercel-secret-value',
    VERCEL_PRODUCTION_TARGET: 'cname.vercel-dns.com',
    R2_ACCOUNT_ID: 'r2-account',
    R2_BUCKET_NAME: 'indicate-media',
    R2_ACCESS_KEY_ID: 'r2-access-key',
    R2_SECRET_ACCESS_KEY: 'r2-secret-key',
    MEDIA_MAX_BYTES: '10485760',
    MEDIA_UPLOAD_TTL_SECONDS: '600',
    MEDIA_READ_TTL_SECONDS: '300',
    MEDIA_ALLOWED_TYPES: 'image/jpeg,image/png,image/webp,image/avif',
    UPSTASH_REDIS_REST_URL: 'https://example.upstash.io',
    UPSTASH_REDIS_REST_TOKEN: 'upstash-secret',
    UPSTASH_REDIS_RESOURCE_ID: 'redis-test-resource',
    REDIS_NAMESPACE: 'indicate:test:v1',
    PUBLISH_MAX_ATTEMPTS: '5',
    PUBLISH_RETRY_DELAYS_SECONDS: '5,30,120,300',
    PUBLISH_LEASE_SECONDS: '30',
    PUBLISH_BATCH_SIZE: '10',
    PUBLISH_FUNCTION_DEADLINE_SECONDS: '50',
    TELEGRAM_BOT_TOKEN: 'telegram-bot-secret',
    TELEGRAM_WEBHOOK_SECRET: 'telegram-webhook-secret',
    GENERIC_WEBHOOK_SECRET: 'generic-webhook-secret',
    TELEGRAM_WEBHOOK_URL: 'https://webhook.indicate.web.id/telegram',
    WEBHOOK_FRESHNESS_SECONDS: '300',
    WEBHOOK_REPLAY_TTL_SECONDS: '900',
    CRON_SECRET: 'cron-secret-value',
    REDACTION_POLICY_VERSION: 'v1',
    CACHE_DEFAULT_TTL_SECONDS: '300',
    CACHE_VERSION: 'v1',
    DEFAULT_LOCALE: 'id-ID',
    SITE_FALLBACK_ASSET_URL: 'https://indicate.web.id/assets/fallback.png',
    ...overrides,
  };
}
